// Generated by gencpp from file vicon_module/Position.msg
// DO NOT EDIT!


#ifndef VICON_MODULE_MESSAGE_POSITION_H
#define VICON_MODULE_MESSAGE_POSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vicon_module
{
template <class ContainerAllocator>
struct Position_
{
  typedef Position_<ContainerAllocator> Type;

  Position_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , speed(0)
    , steering(0)  {
    }
  Position_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)
    , speed(0)
    , steering(0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _theta_type;
  _theta_type theta;

   typedef int32_t _speed_type;
  _speed_type speed;

   typedef int32_t _steering_type;
  _steering_type steering;




  typedef boost::shared_ptr< ::vicon_module::Position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vicon_module::Position_<ContainerAllocator> const> ConstPtr;

}; // struct Position_

typedef ::vicon_module::Position_<std::allocator<void> > Position;

typedef boost::shared_ptr< ::vicon_module::Position > PositionPtr;
typedef boost::shared_ptr< ::vicon_module::Position const> PositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vicon_module::Position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vicon_module::Position_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vicon_module

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'vicon_module': ['/home/nvidia/RosWorkspace/src/vicon_module/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vicon_module::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vicon_module::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vicon_module::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vicon_module::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vicon_module::Position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vicon_module::Position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vicon_module::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5dc7fc87da5e567d1717537bf7c988eb";
  }

  static const char* value(const ::vicon_module::Position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5dc7fc87da5e567dULL;
  static const uint64_t static_value2 = 0x1717537bf7c988ebULL;
};

template<class ContainerAllocator>
struct DataType< ::vicon_module::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vicon_module/Position";
  }

  static const char* value(const ::vicon_module::Position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vicon_module::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
float32 theta\n\
int32 speed\n\
int32 steering\n\
";
  }

  static const char* value(const ::vicon_module::Position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vicon_module::Position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
      stream.next(m.speed);
      stream.next(m.steering);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vicon_module::Position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vicon_module::Position_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed);
    s << indent << "steering: ";
    Printer<int32_t>::stream(s, indent + "  ", v.steering);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VICON_MODULE_MESSAGE_POSITION_H
