// Generated by gencpp from file vicon_module/ViconData.msg
// DO NOT EDIT!


#ifndef VICON_MODULE_MESSAGE_VICONDATA_H
#define VICON_MODULE_MESSAGE_VICONDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <vicon_module/Position.h>

namespace vicon_module
{
template <class ContainerAllocator>
struct ViconData_
{
  typedef ViconData_<ContainerAllocator> Type;

  ViconData_()
    : header()
    , obj_num(0)
    , positions()  {
    }
  ViconData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , obj_num(0)
    , positions(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _obj_num_type;
  _obj_num_type obj_num;

   typedef std::vector< ::vicon_module::Position_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::vicon_module::Position_<ContainerAllocator> >::other >  _positions_type;
  _positions_type positions;




  typedef boost::shared_ptr< ::vicon_module::ViconData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vicon_module::ViconData_<ContainerAllocator> const> ConstPtr;

}; // struct ViconData_

typedef ::vicon_module::ViconData_<std::allocator<void> > ViconData;

typedef boost::shared_ptr< ::vicon_module::ViconData > ViconDataPtr;
typedef boost::shared_ptr< ::vicon_module::ViconData const> ViconDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vicon_module::ViconData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vicon_module::ViconData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vicon_module

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'vicon_module': ['/home/nvidia/RosWorkspace/src/vicon_module/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vicon_module::ViconData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vicon_module::ViconData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vicon_module::ViconData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vicon_module::ViconData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vicon_module::ViconData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vicon_module::ViconData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vicon_module::ViconData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b435bcf2ed522951cf63edc41de10212";
  }

  static const char* value(const ::vicon_module::ViconData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb435bcf2ed522951ULL;
  static const uint64_t static_value2 = 0xcf63edc41de10212ULL;
};

template<class ContainerAllocator>
struct DataType< ::vicon_module::ViconData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vicon_module/ViconData";
  }

  static const char* value(const ::vicon_module::ViconData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vicon_module::ViconData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
int32 obj_num\n\
Position[] positions\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: vicon_module/Position\n\
float32 x\n\
float32 y\n\
float32 theta\n\
int32 speed\n\
int32 steering\n\
";
  }

  static const char* value(const ::vicon_module::ViconData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vicon_module::ViconData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.obj_num);
      stream.next(m.positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ViconData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vicon_module::ViconData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vicon_module::ViconData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "obj_num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.obj_num);
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::vicon_module::Position_<ContainerAllocator> >::stream(s, indent + "    ", v.positions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VICON_MODULE_MESSAGE_VICONDATA_H
